name: Run schemachange
on: [push]

jobs:
  run-schemachange:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install schemachange
      run: |
        pip install schemachange
    - name: Run schemachange
      env:
        SNOWFLAKE_ACCOUNT: ce27782.central-india.azure
        SNOWFLAKE_USER: PUJARAY
        SNOWFLAKE_PASSWORD: Puj@@123RAY
        SNOWFLAKE_DATABASE: DEMO_DB
        SNOWFLAKE_WAREHOUSE: COMPUTE_WH
        SNOWFLAKE_ROLE: ACCOUNTADMIN
      run: |
        schemachange $GITHUB_WORKSPACE/snowflake --account ${SNOWFLAKE_ACCOUNT} \ --user ${SNOWFLAKE_USER} \ --password ${SNOWFLAKE_PASSWORD} \ --database ${SNOWFLAKE_DATABASE} \ --role ${SNOWFLAKE_ROLE}
